### ISSUE TITLE
Use Worker in a non full Hoa environment

### ISSUE THREAD

**Issue by shulard** [hoaproject/Worker#12]
Hello,

I'm currently working on a bot crawler project and I really need to implement a worker system to boost performances.

I try to use this lib in a test project but I get an issue with the "WID" storage path.

I try to update the default path with the code :
```php
<?php
Hoa\Core\Core::getInstance()->setProtocol(
    'hoa://Data/Variable/Run',
    '/an/awesome/path'
);
```

It update the folder but maintain a predefined structure `Variable/Run/....wid`. Is there a way to define a totally specific folder to store the `wid` files ? Or is there a way to automatically generate the base structure folder to start working without problems ?

Thanks ;)

**Comment by shulard** [comment]
Maybe it's relative to the `Hoa\Core\Core::setProtocol` method ? I've checked inside but I didn't found a way to do it properly...

**Comment by Hywan** [comment]
If you try with:
```php
Hoa\Core\Core::getInstance()->setProtocol(
    'hoa://Data/Variable/Run',
    '/an/awesome/path'
);
```
and then print this:
```php
var_dump(resolve('hoa://Data/Variable/Run', false, true));
```
What do you get?

**Comment by Hywan** [comment]
Here is the solution:
```php
$path = 'hoa://Data/Variable/Run';

var_dump(resolve($path, false, true));

/**
 * Will output:
 *     array(1) { [0] => string(…) "<almost pwd>/Data/Variable/Run" }
 */

Hoa\Core::getInstance()->setProtocol($path, "\r" . '/foo/bar');

var_dump(resolve($path, false, true));
/**
 * Will output:
 *     array(1) { [0] => string(8) "/foo/bar" }
 */
```
Note the `\r` to force to not happen `/foo/bar` to the resolution of `hoa://Data/Variable`.

Now, if the provided path exists, then `resolve($path)` will be enough. The second parameter checks whether the path exists or not and the third one unfolds all the possible values (because one path can be resolved to many, that's a cool trick actually ;-)).

**Comment by shulard** [comment]
Ok, I got it ;)

Thanks!
I suggest added a documentation note about that "\r" trick... I've also encountered a path issue with the trailing / that must be present when the wid path is built. I've checked the Core and see that hoaproject/Core#45 issue and hoaproject/Core#64 PR are related...

**Comment by Hywan** [comment]
Yup, there is some work about the documentation of `Hoa\Core`. I am a little ashamed :-(.

**Comment by Hywan** [comment]
I am preparing a contributor guide and some tools to help everyone get an overview of the work. Hope it will help much more!
