### ISSUE TITLE
French doc improvement

### ISSUE THREAD

**Issue by osaris** [hoaproject/Worker#15]
It seems to have a small typo here : 

https://github.com/hoaproject/Worker/blob/535561e24ed224e41036e8e2bacc4a4989da0302/Documentation/Fr/Index.xyl#L56

but also an error of meaning because "dans le cas échéant" isn't appropriate here, we should rather use "dans le cas contraire" nope ?

**Comment by Hywan** [comment]
@osaris Correct! My bad, sorry. Do you have time for a PR?

**Comment by osaris** [comment]
@Hywan I will do it !

**Comment by Hywan** [comment]
Awesome :-).

**Comment by osaris** [comment]
PR #17 added.

**Comment by Hywan** [comment]
@osaris And merged.

**Comment by Hywan** [comment]
(sorry for the “invalid” label, a mistake).
