### ISSUE TITLE
Translate documentation into English

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Worker#4]
- [x] Introduction
- [x] Worker partagé
  - [x] Où sont stockés les profils wid ?
- [x] Communiquer avec un worker
- [x] Utiliser les commandes dédiées
- [x] Conclusion

**Comment by osaris** [comment]
I'm starting working on this one.

**Comment by Hywan** [comment]
Awesome! Feel free to update the checkboxes or use them in your PR (please, do a PR to see the progress).
